# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-Protocol-http-SocksChain10
version:      1.2
version_from: SocksChain10.pm
installdirs:  site
requires:
    Net::SC:                       1.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
